### ISSUE TITLE
Palm trees not working

### ISSUE THREAD

**Issue by ZephaniahNoah** [supermassimo/DynamicTrees-BYG#7] opened 2022-06-30 22:39 UTC
Some palm trees are dynamic trees but sometimes they aren't.
![2022-06-30_12 38 40](https://user-images.githubusercontent.com/14168013/176790160-f4f85b07-193e-4a78-b76a-7cfedae38643.png)

**Comment by ghost** [comment] 2022-07-15 16:30
I have this issue too

**Comment by ghost** [comment] 2022-07-22 14:00
Does anyone have a workaround for this? I'm using Open Terrain Generator and I still can't remove these ugly trees

**Comment by ZephaniahNoah** [comment] 2022-07-22 21:16
I am using TerraForged. I have not found a solution unfortunately.

**Comment by ghost** [comment] 2022-07-23 10:47
My workaround is to only use byg:rocky_beach and disable all other beaches. Still spawns in some broken palms, but less frequently

**Comment by Harleyoc1** [comment] 2022-08-04 10:05
Duplicate of #5

**Closed as completed by Harleyoc1** 2022-08-04 10:05 UTC

**Comment by ZephaniahNoah** [comment] 2022-08-05 01:08
What!?!? How did I miss that? Sorry. My bad.
